name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          pushd ./sidecar/scripts/
          type test.ps1 >> test.ps1
          popd
        azPSVersion: "latest"
        
    - name: logout
      run: |
       az logout
